services:
  php:
    image: ibrahimgunduz34/php-app-reactphp
    build:
      context: .
      dockerfile: ./php-reactphp.dev.Dockerfile
    volumes:
      - .:/var/app
    deploy:
      replicas: 3

  nginx:
    image: ibrahimgunduz34/nginx
    build:
      context: .
      dockerfile: ./nginx-multiple-reactphp.Dockerfile
    ports:
      - 80:8080

  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - database_data:/var/lib/postgresql/data:rw


volumes:
  database_data:
