services:
  php:
    image: ibrahimgunduz34/php-app-mysql
    build:
      context: ../
      dockerfile: ./docker/php-fpm-mysql-dev.Dockerfile
    volumes:
      - ../:/var/app
      - ../.env-mysql:/var/app/.env

  nginx:
    image: ibrahimgunduz34/nginx
    build:
      context: ../
      dockerfile: ./docker/nginx.Dockerfile
    ports:
      - 80:8080

  database:
    image: mariadb:11.1.3
    environment:
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_ROOT_PASSWORD: ${MARIADB_PASSWORD}
    volumes:
      - database_data:/var/lib/mysql:rw


volumes:
  database_data:
