services:
  php:
    image: ibrahimgunduz34/php-app-reactphp-opcache-pgsql
    build:
      context: ../
      dockerfile: ./docker/php-reactphp-opcache.dev.Dockerfile
    volumes:
      - ../:/var/app
      - ../.env-pgsql:/var/app/.env
    ports:
      - 80:8080

  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - database_data:/var/lib/postgresql/data:rw


volumes:
  database_data:
