services:
  php:
    image: ibrahimgunduz34/php-app-reactphp-opcache-mysql
    build:
      context: ../
      dockerfile: ./docker/php-reactphp-opcache-mysql-dev.Dockerfile
    volumes:
      - ../:/var/app
      - ../.env-mysql:/var/app/.env
    ports:
      - 80:8080

  database:
    image: mariadb:11.1.3
    environment:
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_ROOT_PASSWORD: ${MARIADB_PASSWORD}
    volumes:
      - database_data:/var/lib/mysql:rw

volumes:
  database_data:
